### ISSUE TITLE
Needs to be more mobile responsive

### ISSUE THREAD

**Issue by Lilyheart** [Lilyheart/yelp-camp#2]
# Task
## Description

- [ ] Configure the viewport
- [ ] Use legible font sizes
- [ ] Size tap targets appropriately

From [testmysite @ thinkwithgoogle](https://testmysite.thinkwithgoogle.com/)
